import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
// import useStoreState from 'use-store-state';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

// const initialTheme = window.matchMedia('(prefers-color-scheme: dark)').matches
// 	? 'dark'
// 	: 'light';

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// const [theme, setTheme] = useStoreState<'light' | 'dark'>(
	// 	'raspodium-theme',
	// 	initialTheme
	// );

	return (
		<html lang='en'>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
